name: brutus
description: shared proto messages
version: 0.0.1
repository: https://github.com/mattgonewild/brutus/proto/dart

environment:
  sdk: ^3.2.4

dependencies:
  fixnum: ^1.1.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
